BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_MOVIMENTO_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE PKG_FINANCEIRO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MOVIMENTO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/