BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER TRG_MOVIMENTO_BI';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN
      RAISE;
    END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_MOVIMENTO_BI
BEFORE INSERT ON MOVIMENTO
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SEQ_MOVIMENTO.NEXTVAL;
  END IF;

  IF :NEW.DATA_HORA IS NULL THEN
    :NEW.DATA_HORA := SYSTIMESTAMP;
  END IF;

  IF :NEW.CREATED_AT IS NULL THEN
    :NEW.CREATED_AT := SYSTIMESTAMP;
  END IF;

  :NEW.UPDATED_AT := SYSTIMESTAMP;

  IF :NEW.ATIVO IS NULL THEN
    :NEW.ATIVO := 1;
  END IF;
END;
/
SHOW ERRORS TRIGGER TRG_MOVIMENTO_BI
/